### ISSUE TITLE
First event

### ISSUE THREAD

**Issue by simoneb** [nodeschool/vienna#2]
I'm creating this issue to serve as a placeholder to organize the first event in Vienna. Feel free to update this as we have more info. As I understand it might be on the 8th of May, it would be nice to start collecting subscriptions for attendants and mentors (using eventbrite or the likes).

I'm not yet sure I'll attend as I'm not in the area, but I would like to. I attended to one NodeSchool event before as a mentor so if you would like more info feel free to ask.

**Comment by martinheidegger** [comment]
First event done :)
