### ISSUE TITLE
Any upcoming events?

### ISSUE THREAD

**Issue by robaxelsen** [nodeschool/vienna#4]
Hi. I am interested in co-organizing another Vienna event. I am a nodejs beginner, but could contribute with booking/organizing/hosting, etc. Any events planned or in the works?

**Comment by martinheidegger** [comment]
I will be in Vienna from end of July to end of August. I could do mentoring in that period

**Comment by robaxelsen** [comment]
Sounds great! I've never organized a nodeschool event before, but seems straight forward enough. I'll email you some questions, and proposal for dates, if that's ok with you.

**Comment by martinheidegger** [comment]
Sure, but I will also answer them here or at https://gitter.im/martinheidegger

**Comment by robaxelsen** [comment]
Sounds good. Will talk on gitter.

**Comment by martinheidegger** [comment]
Okay, we arranged that.
